server:
  port: 8181

spring:
  application:
    name: task-manager
  profiles:
    active: localstack #@activatedProperties@
  data:
    mongodb:
      host: ${MONGODB_SERVER:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:mongodb_hiveplace}
      username: ${MONGODB_USERNAME:hiveplace}
      password: ${MONGODB_PASSWORD:hiveplace}
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
    session:
      store-type: redis
      redis:
        flush-mode: on-save
        namespace: task-manager:sessions

tasks:
  bucket:
    name: task-manager
  queue:
    url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/task-manager

logging:
  level:
    com:
      amazonaws: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html